language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest
